## Write a Numpy program to compute the multiplication of two given matrixes

In [ ]:
import numpy as np 

x = ([0 , 9 , 2],[8 , 6 , 3 ],[5 , 10 , 3]) 

y = ([6 , 4 , 9],[9 , 3 , 7 ],[2 , 5 , 6]) 

result = np.dot(x,y)

print('matrix(1)=', x)

print('matrix(2)=', y)

print("the multiplication result = ")

print(result)

matrix(1)= ([0, 9, 2], [8, 6, 3], [5, 10, 3])
matrix(2)= ([6, 4, 9], [9, 3, 7], [2, 5, 6])
the multiplication result = 
[[ 85  37  75]
 [108  65 132]
 [126  65 133]]

## Write a NumPy program to compute the determinant of a given square array

In [ ]:
import numpy as np

x = np.array([[9, 0], [4, 8]])

def determinant(array):
    
    return np.linalg.det(array)

print("array =", x)

print("The determinant is =" ,determinant(x))



array = [[9 0]
 [4 8]]
The determinant is = 72.0

## Write a NumPy program to compute the cross product of two given vectors

In [ ]:
import numpy as np
x = [[9, 2], [4, 8]]

y = [[5, 3], [6, 10]]

result1 = np.cross(x,y)

result2 = np.cross(y,x)

print('matrix(1)=', x)

print('matrix(2)=', y)

print("cross product of (x , y):" , result1)

print("cross product of (y , x):" , result2)



matrix(1)= [[9, 2], [4, 8]]
matrix(2)= [[5, 3], [6, 10]]
cross product of (x , y): [17 -8]
cross product of (y , x): [-17   8]

## Write a NumPy program to compute the condition number of a given matrix

In [ ]:
import numpy as np

x = np.array([[0 , 2, -3], [2, 1, 0], [7, 0, 9]])

def conditionNumber(matrix):
    
    return np.linalg.cond(matrix)

print("matrix:", x)

print("The condition number of matrix:",conditionNumber(x))



In [ ]:
import numpy as np

from numpy import linalg as mp

x = np.array([[0 , 2, -3], [2, 1, 0], [7, 0, 9]])

print("matrix:", x)

print("The condition number of matrix:",mp.cond(x))

matrix: [[ 0  2 -3]
 [ 2  1  0]
 [ 7  0  9]]
The condition number of matrix: 29.77332004373927

## Write a NumPy program to compute the inverse of a given matrix

In [ ]:
import numpy as np
x = [[2,2],[4,8]]

y = np.array(x)

result =  np.linalg.inv(y)

print("matrix:", y)

print("Inverse of matrix:" , result)



matrix: [[2 2]
 [4 8]]
Inverse of matrix: [[ 1.   -0.25]
 [-0.5   0.25]]